In [1]:
import numpy as np
import pandas as pd
import random
import numpy as np

# Importando o DataSet

In [2]:
df = pd.read_csv("Rice_Cammeo_Osmancik.csv",delimiter=";",decimal=",")
df.reset_index(inplace=True,drop=True)


In [3]:
df

Area   Perimeter  Major_Axis_Length  Minor_Axis_Length  Eccentricity  \
0     15231  525.578979         229.749878          85.093788      0.928882   
1     14656  494.311005         206.020065          91.730972      0.895405   
2     14634  501.122009         214.106781          87.768288      0.912118   
3     13176  458.342987         193.337387          87.448395      0.891861   
4     14688  507.166992         211.743378          89.312454      0.906691   
...     ...         ...                ...                ...           ...   
3805  11441  415.858002         170.486771          85.756592      0.864280   
3806  11625  421.390015         167.714798          89.462570      0.845850   
3807  12437  442.498993         183.572922          86.801979      0.881144   
3808   9882  392.296997         161.193985          78.210480      0.874406   
3809  11434  404.709992         161.079269          90.868195      0.825692   

      Convex_Area    Extent     Class  
0           15617  0.572896    Cammeo  
1           15072  0.615436    Cammeo  
2           14954  0.693259    Cammeo  
3           13368  0.640669    Cammeo  
4           15262  0.646024    Cammeo  
...           ...       ...       ...  
3805        11628  0.681012  Osmancik  
3806        11904  0.694279  Osmancik  
3807        12645  0.626739  Osmancik  
3808        10097  0.659064  Osmancik  
3809        11591  0.802949  Osmancik  

[3810 rows x 8 columns]

# Separar em matrizes de atributos e vetores de classe

In [4]:
X = df.drop('Class',axis=1)
y = df[['Class']]

# Separar em 10 folds

A função <b>tenfond_manual</b> irá criar uma lista de índices com 10 elementos, sendo cada elemento um fold

In [115]:
def tenfold_manual(df,seed=420):
    intervalo = np.arange(start = 0, stop = len(df))
    random.Random(seed).shuffle(intervalo) #random.Random(seed) define uma seed para o random usar
    
    return np.array_split(intervalo, 10)

A função <b>retorna_fold</b> irá auxiliar os folds a serem acessados durante o for 

In [116]:
def retorna_fold(fold,pos):
    train_index = []
    test_index = folds[pos]
    contador = 0
    for i in folds:
        if contador != pos:
            for j in i:
                train_index.append(j)
        contador += 1
    return train_index,test_index

In [117]:
folds = tenfold_manual(df)

In [118]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import matplotlib as plt

clf = DecisionTreeClassifier(criterion="entropy")

for n in range(10):
    train, test = retorna_fold(folds,n)
    X_train = X.iloc[train]
    y_train = y.iloc[train]
    
    X_test = X.iloc[test]
    y_test = y.iloc[test]
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)

    print(f"Fold: {n+1} \nMatriz de confusão:\n{confusion_matrix(y_test, y_pred)}\n")
    print(f"Classification Report:\n{classification_report(y_test, y_pred)}\n")
    

Fold: 1 
Matriz de confusão:
[[148  12]
 [ 24 197]]

Classification Report:
              precision    recall  f1-score   support

      Cammeo       0.86      0.93      0.89       160
    Osmancik       0.94      0.89      0.92       221

    accuracy                           0.91       381
   macro avg       0.90      0.91      0.90       381
weighted avg       0.91      0.91      0.91       381


Fold: 2 
Matriz de confusão:
[[140  27]
 [ 17 197]]

Classification Report:
              precision    recall  f1-score   support

      Cammeo       0.89      0.84      0.86       167
    Osmancik       0.88      0.92      0.90       214

    accuracy                           0.88       381
   macro avg       0.89      0.88      0.88       381
weighted avg       0.88      0.88      0.88       381


Fold: 3 
Matriz de confusão:
[[145  23]
 [ 21 192]]

Classification Report:
              precision    recall  f1-score   support

      Cammeo       0.87      0.86      0.87       168
    Osm